// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYdyhFgHwjdE4jt1bgNmNqNDdMW9xGdY',
    appId: '1:369655186247:web:4d672cbc2e9e8b84468262',
    messagingSenderId: '369655186247',
    projectId: 'watchscnd',
    authDomain: 'watchscnd.firebaseapp.com',
    storageBucket: 'watchscnd.firebasestorage.app',
    measurementId: 'G-QTY5YYY4T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByF2cXCyIhp1d5SZ_xk41i20_5BqGFVe4',
    appId: '1:369655186247:android:50024b8b47307382468262',
    messagingSenderId: '369655186247',
    projectId: 'watchscnd',
    storageBucket: 'watchscnd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYiNlAl5rxC4aAzS09FAKKW_TkQrErPWc',
    appId: '1:369655186247:ios:f1bececa4478c458468262',
    messagingSenderId: '369655186247',
    projectId: 'watchscnd',
    storageBucket: 'watchscnd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYiNlAl5rxC4aAzS09FAKKW_TkQrErPWc',
    appId: '1:369655186247:ios:f1bececa4478c458468262',
    messagingSenderId: '369655186247',
    projectId: 'watchscnd',
    storageBucket: 'watchscnd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByYdyhFgHwjdE4jt1bgNmNqNDdMW9xGdY',
    appId: '1:369655186247:web:34a279fa6357b871468262',
    messagingSenderId: '369655186247',
    projectId: 'watchscnd',
    authDomain: 'watchscnd.firebaseapp.com',
    storageBucket: 'watchscnd.firebasestorage.app',
    measurementId: 'G-JNQDBKTVYV',
  );
}
